version: "3.9"
services:
  postgres:
    container_name: postgresql
    image: postgres:15
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mcp-net

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "4000:80"
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - mcp-net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  mcp-net:
    driver: bridge
